# Server settings  
server:  
    port: 80
    address: localhost  
  
# DATASOURCE  
jdbc:  
    driverClass: com.mysql.jdbc.Driver  
    url: jdbc:mysql://xx.xx.xx.xx:3306/test?useUnicode=true&characterEncoding=utf-8  
    username: root 
    password: admin
  
# SPRING PROFILES  
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  

    mvc.view:
        prefix: /WEB-INF/
        suffix: .jsp
          
# MyBatis  
mybatis:  
    typeAliasesPackage: springboot_demo.bean 
    mapperLocations: classpath:/**/mapper/*.xml  
    configLocation: classpath:/mybatis-config.xml  
  
# LOGGING  
logging:  
    level:  
       com.ibatis:DEBUG  